#!/usr/bin/env ruby
#
# Copyright 2007 David Shakaryan <omp@gentoo.org>
# Copyright 2007 Brenden Matthews <brenden@rty.ca>
#
# Distributed under the terms of the GNU General Public License v3

require 'omploader'

begin
  db = db_connect
  run_cron(db)
  db.commit
rescue Mysql::Error => err
  db.rollback if !db.nil? if !db.nil?
  $stderr.puts 'MySQL error in cron script: ' + err
rescue
  db.rollback if !db.nil? if !db.nil?
  $stderr.puts 'Error in cron script'
end
