#!/usr/bin/env ruby
#
# Copyright 2007 David Shakaryan <omp@gentoo.org>
# Copyright 2007 Brenden Matthews <brenden@rty.ca>
#
# Distributed under the terms of the GNU General Public License v3

require 'omploader'
require 'tempfile'
require 'rubygems'
require 'id3lib'
require 'mmap'
require 'vorbisfile'
require 'sanitize'

db = db_connect

FCGI.each_cgi {|cgi|
  db_check(db)
  register_visit(cgi, db)

  owner_id = get_owner_id(cgi, db)
  
  comment_name = ''
  comment_body = ''

  if cgi.has_key?('comment')
    comment_body = cgi['comment'].read.to_s
    comment_name = cgi['name'].read.to_s
    id_b64 = cgi['id'].read
    id = from_b64(id_b64)
    comment_body = sanitize(comment_body)
    comment_name = sanitize(comment_name, '')
    begin
      if !comment_body.empty?
        # Insert our new comment into db
        db.query('begin')
        query = db.prepare('insert into comments_body (body) values (?)')
        comment_id = query.execute(comment_body).insert_id
        if comment_name.empty?
          comment_name = 'some luser'
        end
        query = db.prepare('insert into comments (comment_id, metadata_id, owner_id) values (?,?,?)')
        query.execute(comment_id, id, comment_owner_id)
        query = db.prepare('update metadata set comment_count = comment_count + 1 where id = ?')
        query.execute(id)
        query = db.prepare('update owners set name = ? where owner_id = ?')
        query.execute(owner_id)
        db.commit
      end
    rescue
      db.rollback
    end
  else
    id_b64 = cgi['id']
    id = from_b64(id_b64)
  end

#  cgi.out("text/plain") { id + ' pee ' + id_b64 + comment_name + ' : ' + comment_body }
#  next

  # Verify that id is strictly numeric.
  if id =~ /\A\d+\z/
    query = db.prepare('select
        names.name,
        metadata.size,
        metadata.hits,
        metadata.comment_count,
        metadata.creation_time,
        content_types_main.type,
        content_types_sub.type
      from
        metadata
        inner join names on names.id = metadata.name_id
        inner join content_types on content_types.id = metadata.content_type_id
        inner join content_types_main on content_types_main.id = content_types.content_type_main_id
        inner join content_types_sub on content_types_sub.id = content_types.content_type_sub_id
      where
        metadata.id = ?')
    query.execute(id)

    # Verify that id exists in database.
    if query.num_rows > 0
      info = query.fetch
      name = info[0]
      size = info[1]
      hits = info[2].to_s
      comment_count = info[3].to_i
      creation_time = info[4].to_s
      content_type_main = info[5].to_s
      content_type_sub = info[6].to_s
      content_type = content_type_main + '/' + content_type_sub

      # get and process referrers
      query = db.prepare('select
            referrers.address,
	    referrals.count
          from
            metadata
            inner join referrals on referrals.metadata_id = metadata.id
	    inner join referrers on referrers.id = referrals.referrer_id
          where
            metadata.id = ?
	  order by referrals.count desc
	  limit 3  
	    ')
      referrers = ''
      query.execute(id).num_rows.times do
        res = query.fetch
        address = res[0].to_s
        count = res[1].to_s
        referrers += '          <div class="left">' + count + ' from</div><div class="right"><a href="' + address + '">' + address + '</a></div><br class="clear" />' + "\n"
      end
      referrers = '          No referrers!' + "\n" if referrers.empty?

      if size > 1024*1024
        n = (size.to_i/1024.0/1024.0).to_s
        size = n.split('.')[0] + '.' + n.split('.')[1][0...2] + ' MiB'
      elsif size > 1024
        n = (size.to_i/1024.0).to_s
        size = n.split('.')[0] + '.' + n.split('.')[1][0...2] + ' KiB'
      elsif size == 1
        size = size.to_s + ' byte'
      else
        size = size.to_s + ' bytes'
      end

      query = db.prepare('select name from owners where id = ?')
      owner_name = query.execute(owner_id).fetch.to_s
        
      if comment_count > 0
        query = db.prepare('select
            comments.creation_date,
            comments_body.body
          from
            comments
            inner join metadata on metadata.id = comments.metadata_id
            inner join comments_body on comments_body.id = comments.comment_id
          where
            metadata.id = ?
          order by comments.creation_date asc
            ')
        comments_body =
          '        <div class="title">Comments</div>' + "\n"
        query.execute(id).num_rows.times do
          res = query.fetch
          date = res[0].to_s
          body = res[1].to_s
          comments_body +=
            '        <div class="content" align="left">' + "\n" +
            '          <strong>At ' + date + ' ' + owner_name + ' wrote:</strong>' + "\n" +
            '          <p><em><pre>' + body + '</pre></em></p>' + "\n" +
            '        </div>' + "\n"
        end
      end
      comment_form =
        '        <form enctype="multipart/form-data" action="i' + id_b64 + '" method="post">' + "\n" +
        '          <div class="form">' + "\n" +
        '            <div class="float name left-align">' + "\n" +
        '              <div class="label">Name</div>' + "\n" +
        '              <input type="line" name="name" size="25" class="input field" value="' + owner_name + '" />' + "\n" +
        '            </div>' + "\n" +
        '            </div>' + "\n" +
        '            <br class="clear" />' + "\n" +
        '            <div class="float"><textarea name="comment" class="input"></textarea></div>' + "\n" +
        '            <br class="clear" />' + "\n" +
        '            <input type="hidden" name="id" value="' + id_b64 + '" />' + "\n" +
        '            <input type="submit" value="Post comment" class="button" />' + "\n" +
        '          </div>' + "\n" +
        '        </form>'

      meta = ''
      if content_type_main == 'image'
        file_link = '<img src="t' + id_b64 + '" alt="View file!" />'
      elsif content_type == 'audio/mpeg' or content_type == 'application/ogg'
        query = db.prepare('select
            data.datum
          from
            metadata inner join data on data.id = metadata.datum_id
          where
            metadata.id = ?')
        res = query.execute(id).fetch
        tmp = Tempfile.new(name)
        tmp.close
        mmap = Mmap.new(tmp.path, 'rw')
        mmap.insert(0, res[0])
        if content_type == 'audio/mpeg'
          tag = ID3Lib::Tag.new(tmp.path)
          artist = tag.artist
          title = tag.title
          album = tag.album
          year = tag.year
        elsif content_type == 'application/ogg'
          vf = Ogg::VorbisFile.new
          tmp.open
          if vf.open(tmp)
            comments = vf.comments(-1)
            artist = comments['artist']
            title = comments['title']
            album = comments['album']
            year = comments['date']
          end
        end
        meta += '          <div class="left"><strong>Artist:</strong></div><div class="right">' + artist + '</div><br class="clear" />' + "\n" if artist and !artist.empty?
        meta += '          <div class="left"><strong>Title:</strong></div><div class="right">' + title + '</div><br class="clear" />' + "\n" if title and !title.empty?
        meta += '          <div class="left"><strong>Album:</strong></div><div class="right">' + album + '</div><br class="clear" />' + "\n" if album and !album.empty?
        meta += '          <div class="left"><strong>Year:</strong></div><div class="right">' + year + '</div><br class="clear" />' + "\n" if year and !year.empty?
        meta = meta.insert(0, '          <br />' + "\n") if !meta.empty?
        file_link = '<img src="_omploader_thumb.png" alt="View file!" />'
      else
        file_link = '<img src="_omploader_thumb.png" alt="View file!" />'
      end

      if !comment_body.empty?
        expiry = Time.now - 100000
      else
        expiry = Time.now + 604800
      end
      cgi.out('type' => 'text/html', 'expires' => expiry) {
        xhtml_pre(' – ' + name + ' (' + content_type + ')') +
        '        <div class="title">Information for ' + id_b64 + '</div>' + "\n" +
        '        <div class="content">' + "\n" +
        '          <div class="thumb automargin"><div class="container"><a href="v' + id_b64 + '">' + file_link + '</a></div></div>' + "\n" +
        '          <div class="left"><strong>Name:</strong></div><div class="right">' + name + '</div><br class="clear" />' + "\n" +
        '          <div class="left"><strong>Size:</strong></div><div class="right">' + size + '</div><br class="clear" />' + "\n" +
        '          <div class="left"><strong>Hits:</strong></div><div class="right">' + hits + '</div><br class="clear" />' + "\n" +
        '          <div class="left"><strong>Upload Time:</strong></div><div class="right">' + creation_time + '</div><br class="clear" />' + "\n" +
        '          <div class="left"><strong>Content Type:</strong></div><div class="right">' + content_type + '</div><br class="clear" />' + "\n" +
        meta +
        '        </div>' + "\n" +
        '        <div class="title">Top referrers</div>' + "\n" +
        '        <div class="content">' + "\n" +
        referrers +
        '        </div>' + "\n" +
        comments_body +
        '        <div class="content">' + "\n" +
        comment_form +
        '        </div>' + "\n" +
        xhtml_post
      }
    else
      cgi.out('text/html') {
        xhtml_pre + '        <div class="content large">Nothing to pee here.</div>' + xhtml_post
      }
    end
  else
    cgi.out('text/html') {
      xhtml_pre + '        <div class="content large">You are a trad.</div>' + xhtml_post
    }
  end
}
