#!/bin/env ruby
#
# $Id$
#
# Copyright 2007 David Shakaryan <omp@gentoo.org>
# Copyright 2007 Brenden Matthews <brenden@rty.ca>
#
# Distributed under the terms of the GNU General Public License v3
#

require 'omploader'

begin
	db = db_connect
	run_cron(db)
	db.commit
rescue Mysql::Error => err
	db.rollback unless db.nil?
	$stderr.puts 'MySQL error in cron script: ' + err
	log = Logger.new(Paths['log'])
	log.error(err)
rescue
	db.rollback unless db.nil?
	$stderr.puts 'Error in cron script'
	log = Logger.new(Paths['log'])
	log.error(err)
end
