#!/bin/env ruby
#
# Copyright 2007-2009 David Shakaryan <omp@gentoo.org>
# Copyright 2007-2009 Brenden Matthews <brenden@rty.ca>
#
# Distributed under the terms of the GNU General Public License v3
#

require 'omploader'
require 'set'

FCGI.each_cgi {|cgi|
	begin
		db = db_connect

		db_check(db)

		top_files =
			"\t\t\t" + '<div class="title">' + "\n" +
			"\t\t\t\t" + 'Random Images' + "\n" +
			"\t\t\t" + '</div>' + "\n" +
			"\t\t\t" + '<div class="content">' + "\n"
		query = db.prepare('select max(id), min(id) from metadata')
		stmt = query.execute
		res = stmt.fetch
		max = res[0].to_i
		min = res[1].to_i
		count = Max_rand
		rands = Set.new
		try = 0
		overall_tries = 0
		while count > 0
			rand_id = rand(max - min) + min
			query = db.prepare('select metadata.id from metadata inner join content_types on content_types.id = metadata.content_type_id inner join content_types_main on content_types_main.id = content_types.content_type_main_id where metadata.id = ? and metadata.valid = ? and (content_types_main.type = "image" or content_types_main.type = "video")')
			stmt = query.execute(rand_id, 1)
			res = stmt.fetch
			num_rows = stmt.num_rows
			stmt.close
			if num_rows < 1
				try += 1
				if try > 15
					count -= 1
					try = 0
				end
			elsif rands.add?(res[0])
				count -= 1
			else
				overall_tries += 1
			end
			if overall_tries > 30
				count = 0
			end
		end
		count = 0
		top_files_info = ''
		rands.each {|id|
			count += 1
			query = db.prepare('select names.name from metadata inner join names on names.id = metadata.name_id where metadata.id = ?')
			stmt = query.execute(id)
			result = stmt.fetch
			stmt.close
			name = result.first.to_s

			top_files += "\t\t\t\t" + '<div class="thumb float"><div class="container"><a href="v' + id.to_s.to_b64 + '"><img src="t' + id.to_s.to_b64 + '" alt="View file!" /></a></div></div>' + "\n"
			top_files_info += "\t\t\t\t" + '<div class="info float"><a href="i' + id.to_s.to_b64 + '">Info</a></div>' + "\n"
			if count % 5 == 0
				top_files += "\t\t\t\t" + '<br class="clear" />' + "\n" + top_files_info + "\t\t\t\t" + '<br class="clear" />' + "\n"
				top_files_info = ''
			end
		}
		if count < Max_rand and count % 5 != 0
			top_files += "\t\t\t\t" + '<br class="clear" />' + "\n" + top_files_info + "\t\t\t\t" + '<br class="clear" />' + "\n" +
				"\t\t\t" + '</div>' + "\n"
		else
			top_files += "\t\t\t" + '</div>' + "\n"
		end

		xhtml =
			"\t\t\t" + '<div class="content large">' + "\n" +
			"\t\t\t\t" + '<a href="r">ENCORE UNE FOIS!</a>' + "\n" +
			"\t\t\t" + '</div>' + "\n" +
			top_files

		cgi.out('application/xhtml+xml') { xhtml_pre('', '', false) + xhtml + xhtml_post }
	rescue Mysql::Error => err
		db.rollback unless db.nil?
		if Debug
			errmsg = err.to_s + '<br />' + err.backtrace.join('<br />')
		else
			errmsg = err.to_s
		end
		cgi.out('application/xhtml+xml') {
			xhtml_pre + '        <div class="content large">Ouch, db error: ' + errmsg + '</div>' + xhtml_post
		}
		log = Logger.new(Paths['log'])
		log.error(cgi.host)
		log.error(cgi.script_name)
		log.error(cgi.params)
		log.error(err)
	rescue RuntimeError => err
		db.rollback unless db.nil?
		cgi.out('application/xhtml+xml') {
			xhtml_pre + '        <div class="content large">' + err + '</div>' + xhtml_post
		}
	rescue SyntaxError, NameError => err
		db.rollback unless db.nil?
		if Debug
			errmsg = err.to_s + '<br />' + err.backtrace.join('<br />')
		else
			errmsg = err.to_s
		end
		cgi.out('application/xhtml+xml') {
			xhtml_pre + '        <div class="content large">Oops, we screwed up.  String won\'t compile: ' + errmsg + '</div>' + xhtml_post
		}
		log = Logger.new(Paths['log'])
		log.error(cgi.host)
		log.error(cgi.script_name)
		log.error(cgi.params)
		log.error(err)
	rescue StandardError => err
		db.rollback unless db.nil?
		if Debug
			errmsg = err.to_s + '<br />' + err.backtrace.join('<br />')
		else
			errmsg = err.to_s
		end
		cgi.out('application/xhtml+xml') {
			xhtml_pre + '        <div class="content large">Oops, we screwed up.  Error running script: ' + errmsg + '</div>' + xhtml_post
		}
		log = Logger.new(Paths['log'])
		log.error(cgi.host)
		log.error(cgi.script_name)
		log.error(cgi.params)
		log.error(err)
	rescue MemCache::MemCacheError => err
		db.rollback unless db.nil?
		if Debug
			errmsg = err.to_s + '<br />' + err.backtrace.join('<br />')
		else
			errmsg = err.to_s
		end
		cgi.out('application/xhtml+xml') {
			xhtml_pre + '        <div class="content large">Oops, we screwed up.  Error running script: ' + errmsg + '</div>' + xhtml_post
		}
		log = Logger.new(Paths['log'])
		log.error(cgi.host)
		log.error(cgi.script_name)
		log.error(cgi.params)
		log.error(err)
	rescue
		db.rollback unless db.nil?
		if Debug
			errmsg = err.to_s + '<br />' + err.backtrace.join('<br />')
		else
			errmsg = err.to_s
		end
		cgi.out('application/xhtml+xml') {
			xhtml_pre + '        <div class="content large">Oops, we screwed up.  This error isn\'t being handled: ' + err + '</div>' + xhtml_post
		}
		log = Logger.new(Paths['log'])
		log.error(cgi.host)
		log.error(cgi.script_name)
		log.error(cgi.params)
		log.error(err)
	ensure
		db.close if db
	end
}
